Update libcdb.py
This error was found when I executed the script:
-Zer0☠ :commandline$ libcdb file 123 
Traceback (most recent call last):
  File "/home/za0/.local/bin/libcdb", line 8, in <module>
    sys.exit(main())
  File "/home/za0/.local/lib/python3.6/site-packages/pwnlib/commandline/common.py", line 32, in main
    pwnlib.commandline.main.main()
  File "/home/za0/.local/lib/python3.6/site-packages/pwnlib/commandline/main.py", line 58, in main
    commands[args.command](args)
  File "/home/za0/.local/lib/python3.6/site-packages/pwnlib/commandline/libcdb.py", line 215, in main
    log.failure('File does not exist %s', args.file)
AttributeError: 'Namespace' object has no attribute 'file'

It can be successfully executed after correction:
-Zer0☠ :commandline$ libcdb file 123
[-] File does not exist 123